apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: heathsa2
spec:
  id: heathsa2
  compositionSelector:
    matchLabels:
      provider: azure
      cluster: aks
  parameters:
    nodeSize: small
    minNodeCount: 2
    namespaces: #list of vclusters to create
      - dev
    usage:
      # Usage is still in `alpha` and needs to be enabled by add `--set args='{"--enable-usages"}'` to `helm install`.
      enabled: true
    apps:
      crossplane:
        enabled: true
      argocd:
        enabled: true
        host: argocd.44.212.104.169.nip.io
        repoURL: https://github.com/vfarcic/crossplane-kubernetes-gitops
      dapr:
        enabled: false
      istio:
        enabled: true
        hostname: domain.default.com
      traefik:
        enabled: false
      externalSecrets:
        enabled: true
